# Generated by Django 4.0.5 on 2022-06-15 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_usertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('Mon', 'MONDAY'), ('Tue', 'TUESDAY'), ('Thu', 'THURSDAY'), ('Sat', 'SATURDAY'), ('Fri', 'FRIDAY'), ('Wed', 'WEDNESDAY')], max_length=15)),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
