# Generated by Django 4.0.5 on 2022-06-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_doctor_availability_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_availability',
            name='week',
            field=models.IntegerField(choices=[(2, 'WEDNESDAY'), (1, 'TUESDAY'), (3, 'THURSDAY'), (0, 'MONDAY'), (4, 'FRIDAY'), (5, 'SATURDAY')], max_length=15),
        ),
    ]
