# Generated by Django 4.0.5 on 2022-06-15 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_doctor_availability_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_availability',
            name='week',
            field=models.IntegerField(choices=[(5, 'SATURDAY'), (0, 'MONDAY'), (1, 'TUESDAY'), (4, 'FRIDAY'), (3, 'THURSDAY'), (2, 'WEDNESDAY')]),
        ),
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('description', models.TextField(default=None)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Absent'), (3, 'Canceled')], default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_aap', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_app', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
